In [1]:
import pandas as pd 

df1 = pd.DataFrame({
    "id": [1,2,3],
    "customer_id": [1,2,3],
    "customer_name": ["Robert","Peter","Wonsil"],
}, columns=["id", "customer_id", "customer_name"])

df1

   id  customer_id customer_name
0   1            1        Robert
1   2            2         Peter
2   3            3        Wonsil

In [2]:
df2 = pd.DataFrame({
    "id": [1,2,4],
    "order_id": [100,200,300],
    "order_date": ["2025-01-21","2025-02-03","2025-09-01"],
}, columns=["id", "order_id", "order_date"])

df2

   id  order_id  order_date
0   1       100  2025-01-21
1   2       200  2025-02-03
2   4       300  2025-09-01

In [ ]:
#서로 다른 데이터 프레임을 하나로 합치는 방법 
# 1) concat () :  서로 다른 데이터 프레임을 단순 연결 (* 교차되는 특정 인덱스를 고려하지 않음) -> 좌우로도 합칠 수 있고, 상하로도 합칠 수 있음 (상하가 디폴트임)
# 2) merge() : 특정 인덱스를 기준으로 합침

In [3]:
pd.concat([df1, df2])

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       NaN         NaN
1   2          2.0         Peter       NaN         NaN
2   3          3.0        Wonsil       NaN         NaN
0   1          NaN           NaN     100.0  2025-01-21
1   2          NaN           NaN     200.0  2025-02-03
2   4          NaN           NaN     300.0  2025-09-01

In [5]:
doc = pd.concat([df1, df2], axis=0)
doc

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       NaN         NaN
1   2          2.0         Peter       NaN         NaN
2   3          3.0        Wonsil       NaN         NaN
0   1          NaN           NaN     100.0  2025-01-21
1   2          NaN           NaN     200.0  2025-02-03
2   4          NaN           NaN     300.0  2025-09-01

In [6]:
pd.merge(df1, df2) #-> inner join의 기능과 유사하다

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert       100  2025-01-21
1   2            2         Peter       200  2025-02-03

In [7]:
pd.merge(df1, df2, on ="id" )

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert       100  2025-01-21
1   2            2         Peter       200  2025-02-03

In [9]:
pd.merge(df1, df2, on="id", how="outer")

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert     100.0  2025-01-21
1   2          2.0         Peter     200.0  2025-02-03
2   3          3.0        Wonsil       NaN         NaN
3   4          NaN           NaN     300.0  2025-09-01

In [10]:
pd.merge(df1, df2, on="id", how="left")

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert     100.0  2025-01-21
1   2            2         Peter     200.0  2025-02-03
2   3            3        Wonsil       NaN         NaN

In [11]:
pd.merge(df1, df2, on="id", how="right")

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       100  2025-01-21
1   2          2.0         Peter       200  2025-02-03
2   4          NaN           NaN       300  2025-09-01

In [13]:
df1 = df1.set_index("id")
df1

    customer_id customer_name
id
1             1        Robert
2             2         Peter
3             3        Wonsil

In [14]:
df2 = df2.set_index("id")
df2

    order_id  order_date
id
1        100  2025-01-21
2        200  2025-02-03
4        300  2025-09-01

In [15]:
pd.merge(df1, df2, left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1             1        Robert       100  2025-01-21
2             2         Peter       200  2025-02-03

In [16]:
pd.merge(df1, df2, how= "outer", left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1           1.0        Robert     100.0  2025-01-21
2           2.0         Peter     200.0  2025-02-03
3           3.0        Wonsil       NaN         NaN
4           NaN           NaN     300.0  2025-09-01

In [17]:
pd.merge(df1, df2, how= "left", left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1             1        Robert     100.0  2025-01-21
2             2         Peter     200.0  2025-02-03
3             3        Wonsil       NaN         NaN

In [18]:
pd.merge(df1, df2, how= "right", left_index=True, right_index=True)

    customer_id customer_name  order_id  order_date
id
1           1.0        Robert       100  2025-01-21
2           2.0         Peter       200  2025-02-03
4           NaN           NaN       300  2025-09-01

In [19]:
import os 

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
file_list, csv_list = os.listdir(PATH), list()

FileNotFoundError: [Errno 2] No such file or directory: 'COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/'