In [1]:
import pandas as pd 

df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]
})

df

    미국    한국  중국
0  2.1  0.40  10
1  2.2  0.50  13
2  2.3  0.45  15

In [2]:
import pandas as pd 

df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]
}, index=[2000, 2010, 2020])

df

       미국    한국  중국
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [6]:
df.index

Index([2001, 2002, 2003], dtype='int64')

In [5]:
df.index = [2001,2002,2003]

In [8]:
df.columns = ["일본", "필리핀", "러시아"]

In [9]:
df

       일본   필리핀  러시아
2001  2.1  0.40   10
2002  2.2  0.50   13
2003  2.3  0.45   15

In [10]:
df.values

array([[ 2.1 ,  0.4 , 10.  ],
       [ 2.2 ,  0.5 , 13.  ],
       [ 2.3 ,  0.45, 15.  ]])

In [11]:
import pandas as pd 

df = pd.DataFrame({
    "년도": [2000, 2010, 2020],
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]
})

df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [12]:
df = df.set_index("년도")
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [14]:
df.index.name

'년도'

In [15]:
df.index.name = "연도"

In [16]:
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [17]:
df = df.reset_index("연도")
df

     연도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [19]:
df = df.set_index("연도")
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [20]:
df.loc[2000]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [21]:
df.iloc[0]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [22]:
type(df.loc[2000])

pandas.core.series.Series

In [23]:
df["미국"]

연도
2000    2.1
2010    2.2
2020    2.3
Name: 미국, dtype: float64

In [24]:
type(df["미국"])

pandas.core.series.Series

In [28]:
print(df.loc[2010]["미국"])

2.2

In [29]:
import pandas as pd 

df = pd.DataFrame({
    "년도": ["2000", "2010", "2020"],
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]
})

df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [30]:
df = df.set_index("년도")

In [31]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [32]:
df.index

Index(['2000', '2010', '2020'], dtype='object', name='년도')

In [33]:
df ["미국"]

년도
2000    2.1
2010    2.2
2020    2.3
Name: 미국, dtype: float64

In [34]:
df["일본"] = [1,2,3]

In [35]:
df["일본"]

년도
2000    1
2010    2
2020    3
Name: 일본, dtype: int64

In [36]:
del df["일본"]

In [37]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [38]:
df.loc[2021] = [1,2,3]

In [39]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2021  1.0  2.00   3

In [40]:
df.drop([2021])

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [43]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2021  1.0  2.00   3

In [45]:
df.drop([2021], inplace=True)

In [46]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [47]:
df2 = df[["중국","한국"]].copy()

In [48]:
df2

      중국    한국
년도
2000  10  0.40
2010  13  0.50
2020  15  0.45

In [49]:
df2.columns = ["브라질", "아르헨티나"]

In [50]:
df2

      브라질  아르헨티나
년도
2000   10   0.40
2010   13   0.50
2020   15   0.45